const FRAME_RATE = 20;
const CARDS_PATTERN_COUNT = 18;
const ANIMATION_DURATION_FLIP_CARD = 0.5;
const ANIMATION_DURATION_MESSAGE = 3;
const ANIMATION_FRAME_RATE_FLIP_CARD = 20;
const ANIMATION_FRAME_RATE_MESSAGE = 10;

module.exports = {
  FRAME_RATE,
  CARDS_PATTERN_COUNT,
  ANIMATION_DURATION_FLIP_CARD,
  ANIMATION_DURATION_MESSAGE,
  ANIMATION_FRAME_RATE_FLIP_CARD,
  ANIMATION_FRAME_RATE_MESSAGE,
}
